// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATTHO3ik7TaSj7kEHzaQNhlnEOsNtjg8A',
    appId: '1:806913633410:web:416160e2966fd847c1189b',
    messagingSenderId: '806913633410',
    projectId: 'todo-app-caeea',
    authDomain: 'todo-app-caeea.firebaseapp.com',
    storageBucket: 'todo-app-caeea.firebasestorage.app',
    measurementId: 'G-HVP0L731HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYroo23_shdP5iq5UxKfCIO7RGjCT0IlM',
    appId: '1:806913633410:android:1269fae160904893c1189b',
    messagingSenderId: '806913633410',
    projectId: 'todo-app-caeea',
    storageBucket: 'todo-app-caeea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk1kIL0DVqlGgRvMIlW7FOko9elzWLaGU',
    appId: '1:806913633410:ios:9a5a8fe7fc6ec5cdc1189b',
    messagingSenderId: '806913633410',
    projectId: 'todo-app-caeea',
    storageBucket: 'todo-app-caeea.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATTHO3ik7TaSj7kEHzaQNhlnEOsNtjg8A',
    appId: '1:806913633410:web:68c1126e1c203b7ac1189b',
    messagingSenderId: '806913633410',
    projectId: 'todo-app-caeea',
    authDomain: 'todo-app-caeea.firebaseapp.com',
    storageBucket: 'todo-app-caeea.firebasestorage.app',
    measurementId: 'G-4H1E83DF1N',
  );
}
